# Basic traefik.yml example
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
api:
  dashboard: true
  insecure: true 
  
providers:
  docker:
    exposedByDefault: false
    network: proxy

certificatesResolvers:
  letsencrypt:
    acme:
      email: ansigare@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web